config/routes.rb
Rails.application.routes.draw do
  # DEVISE
  devise_for :users,
             controllers: {
               passwords: 'users/passwords',
               confirmations: 'users/confirmations'
             },
             only: [:passwords, :confirmations]

  devise_scope :user do
    get    'sign_up',  to: 'users/registrations#new'
    post   'sign_up',  to: 'users/registrations#create'
    get    'sign_in',  to: 'users/sessions#new'
    post   'sign_in',  to: 'users/sessions#create'
    delete 'sign_out', to: 'users/sessions#destroy'
  end

  get   '/:name',                  to: 'users#show'

  get   '/:name/followers',        to: 'users#followers',           as: 'user_followers'
  get   '/:name/following',        to: 'users#following',           as: 'user_following'
  get   'account/password/change', to: 'users#password_change_new', as: 'new_account_password_change'
  post  'account/password/change', to: 'users#password_change',     as: 'account_password_change'
  post  'set_locale', to: 'home#set_locale', as: 'set_locale'


  resources :users, only: [:edit, :update] do
    collection do
      post   :follow, to: 'users#follow'
      delete :follow, to: 'users#unfollow'
    end

    member do
      post   :like, to: 'users#like'
      delete :like, to: 'users#unlike'
    end

    resources :posts, only: [:new, :create]
  end

  resources :account_edits, only: [:new, :create]

  resources :posts, only: [:update, :destroy] do
    resources :comments, only: [:new, :create]
  end

  resources :comments, only: [:update, :destroy]

  # post   :like_action, to: 'users#like', as: 'user_like'
  # delete :like_action, to: 'users#unlike', as: 'user_unlike'

  root to: 'home#index'
  # Advanced
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  # RELATIONS
  belongs_to :post
  belongs_to :owner, class_name: 'User', foreign_key: 'user_id'

  # QUERYS
  default_scope -> { order(created_at: :desc) }

  # VALIDATIONS
  validates :user_id, presence: true
  validates :post_id, presence: true
  validates :content, presence: true,
                      length: 0..200

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end

  def create
    user = User.find(params[:user_id])
    post = Post.find(params[:post_id])
    @comment = user.comment_on(post, comment_params[:content])

    @comment.save

    redirect_to request.referer || root_url
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :user_id, :post_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li class="o-media o-media--small" data-ui-component="comment">

  <div class="o-media__body">

    <a class="c-post__owner c-link--silence" href=<%="/#{comment.owner.name}" %> >
      <strong><%= comment.owner.name %></strong>
    </a>
    <span><%= comment.content %></span>

  </div>

</li>

app/views/comments/_new_comment.html.erb
<div class="c-post__footer-bar u-padding-vertical-small" default-ui-component="new-comment">

  <% if user_signed_in? %>
    <% if current_user.like?(post) %>
      <%= link_to  "", like_user_path(id: current_user.id, post_id: post.id), method: :delete, class: 'c-icon-main c-icon-main__heart_fill c-post__like-action' %>
    <% else %>
      <%= link_to  "", like_user_path(id: current_user.id, post_id: post.id), method: :post, class: 'c-icon-main c-icon-main__heart_open c-post__like-action' %>
    <% end %>
  <% end %>

  <%= form_for( post.comments.build, url: post_comments_path(post, user_id: current_user.id), html: { class: 'c-post__new-comment c-form c-form--primary'}) do |f| %>

    <%= f.text_field :content, placeholder: "#{t('app.comment_post')} ...", class: 'c-form__control c-form__control--bare' %>

    <%= f.submit t('app.submit'), class: 'c-btn c-btn--primary c-btn--small'     %>
  <% end %>

  <div class="c-icon-main c-icon-main__more-actions"></div>

</div>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>