config/routes.rb
Rails.application.routes.draw do
  # DEVISE
  devise_for :users,
             controllers: {
               passwords: 'users/passwords',
               confirmations: 'users/confirmations'
             },
             only: [:passwords, :confirmations]

  devise_scope :user do
    get    'sign_up',  to: 'users/registrations#new'
    post   'sign_up',  to: 'users/registrations#create'
    get    'sign_in',  to: 'users/sessions#new'
    post   'sign_in',  to: 'users/sessions#create'
    delete 'sign_out', to: 'users/sessions#destroy'
  end

  get   '/:name',                  to: 'users#show'

  get   '/:name/followers',        to: 'users#followers',           as: 'user_followers'
  get   '/:name/following',        to: 'users#following',           as: 'user_following'
  get   'account/password/change', to: 'users#password_change_new', as: 'new_account_password_change'
  post  'account/password/change', to: 'users#password_change',     as: 'account_password_change'
  post  'set_locale', to: 'home#set_locale', as: 'set_locale'


  resources :users, only: [:edit, :update] do
    collection do
      post   :follow, to: 'users#follow'
      delete :follow, to: 'users#unfollow'
    end

    member do
      post   :like, to: 'users#like'
      delete :like, to: 'users#unlike'
    end

    resources :posts, only: [:new, :create]
  end

  resources :account_edits, only: [:new, :create]

  resources :posts, only: [:update, :destroy] do
    resources :comments, only: [:new, :create]
  end

  resources :comments, only: [:update, :destroy]

  # post   :like_action, to: 'users#like', as: 'user_like'
  # delete :like_action, to: 'users#unlike', as: 'user_unlike'

  root to: 'home#index'
  # Advanced
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # RELATIONS
  has_many :active_follow_actions,
           class_name: 'FollowAction',
           foreign_key: 'follower_id',
           dependent: :destroy
  has_many :passive_follow_actions,
           class_name: 'FollowAction',
           foreign_key: 'followed_id',
           dependent: :destroy
  has_many :following, through: :active_follow_actions,
                       source: :followed
  has_many :followers, through: :passive_follow_actions,
                       source: :follower
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :like_actions,
           class_name: 'LikeAction',
           foreign_key: 'user_id',
           dependent: :destroy
  has_many :liked_posts,
           through: :like_actions,
           source: :post


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # VALIDATIONS
  validates :name, presence: true

  # Follow a user
  def follow(other_user)
    following << other_user
  end

  # Unfollow a user
  def unfollow(other_user)
    following.delete(other_user)
  end

  # Return true if current user is following the other user
  def following?(other_user)
    following.include?(other_user)
  end

  def not_following?(other_user)
    !following?(other_user)
  end

  def post_feeds
    following_ids = "SELECT followed_id FROM follow_actions
                        WHERE  follower_id = :user_id"
    Post.where("user_id IN (#{following_ids})
                        OR user_id = :user_id", user_id: id)
  end

  # Like a post
  def like(post)
    liked_posts << post
  end

  # Unlike a post
  def unlike(post)
    liked_posts.delete(post)
  end

  # Return true if user like the post
  def like?(post)
    liked_posts.include?(post)
  end

  class CommentOnInvalidPostError < StandardError
  end

  def comment_on(post, content)
    throw CommentOnInvalidPostError.new if post.invalid?
    throw CommentOnInvalidPostError.new unless post.persisted?

    comment = comments.build(content: content, post_id: post.id, user_id: id)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    sign_in_path
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    sign_in_path
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  def after_resetting_password_path_for(resource)
    sign_in_url
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    sign_in_url
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    "/#{resource.name}"
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # HOOKS
  skip_before_action   :authenticate_user!,   only: [:show]
  before_action        :set_user,             only: [:show,             :followers,    :following]
  before_action        :set_current_user,     only: [:password_change_new, :password_change]
  append_before_action :check_match_password, only: [:password_change]

  # GET /users/1
  # GET /users/1.json
  def show
    @posts = @user.posts.page( params[:page] ).per(9)

    respond_to do |format|
      format.html { render :show }
      format.js { render :show }
    end

  end

  # GET /users/:id/password_change
  # Present a form to allow user to change password
  def password_change_new

  end

  # POST /users/:id/password_change
  # Change user's password.
  # Success conditions:
  # 1. User must provide current_password.
  # 2. password and password confirmation must match.
  def password_change
    respond_to do |format|
      if @user.update_with_password(password_change_params)
        bypass_sign_in(@user)
        format.html { redirect_to request.referer || root_url, notice: 'User password has been successfully updated.' }
      else
        format.html { render 'password_change_new' }
      end
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        UserMailer.user_activate(@user, @user.activation_token).deliver_later
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /users/follow
  def follow
    to_follow = User.find(params[:followed_id])
    if current_user.not_following?(to_follow)
      current_user.follow(to_follow)
      @user = to_follow.reload
      redirect_to request.referer || "/#{to_follow.name}"
    else
      user.errors[:base] << "already follow user #{to_follow.name}"
      redirect_to request.referer || "/#{to_follow.name}"
    end
  end

  # DELETE /users/follow
  def unfollow
    to_unfollow = User.find(params[:followed_id])
    if current_user.following?(to_unfollow)
      current_user.unfollow(to_unfollow)
      redirect_to request.referer || "/#{to_unfollow.name}"
    else
      user.errors[:base] << "can't unfollow if not following #{to_unfollow.name}"
      redirect_to request.referer || "/#{to_unfollow.name}"
    end
  end

  def like
    @post = Post.find(params[:post_id])
    @user = User.find(params[:id])

    if @user.like?(@post)
      @user.errors[:base] << "repeat like."
    else
      @user.like(@post)
      @user = @user.reload
    end

    redirect_to request.referer || root_url
  end

  def unlike
    @post = Post.find(params[:post_id])
    @user = User.find(params[:id])

    if @user.like?(@post)
      @user.unlike(@post)
      @user = @user.reload
    else
      @user.errors[:base] << "repeat unlike."
    end

    redirect_to request.referer || root_url
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by(name: params[:name]) || current_user
    end

    # set current signed in user to @user
    def set_current_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :website, :intro, :password, :password_confirmation)
    end

    def password_change_params
      params.require(:user).permit(:current_password, :password, :password_confirmation)
    end

    def check_match_password
      if password_change_params[:password] != password_change_params[:password_confirmation]
        @user.errors[:password_confirmation] << 'does not match password.'
        render 'password_change_new'
      end
      true
    end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, size: 80, class_name: '') 
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: class_name)
  end
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit 'Submit' %>
  </div>

  <%= render 'shared/error_messages', object: @user %>
<% end %>

app/views/users/_signup_form.html.erb
<%= form_for( user ) do |f| %>
  <%= render 'shared/error_messages', object: user %>

  <div class="field">
    <%= f.text_field :email, placeholder: User.human_attribute_name(:email) %>
  </div>

  <div class="field">
    <%= f.text_field :name, placeholder: User.human_attribute_name(:name) %>
  </div>

  <div class="field">
    <%= f.password_field :password, placeholder: User.human_attribute_name(:password) %>
  </div>

  <div class="field">
    <%= f.password_field :password_confirmation, User.human_attribute_name(:password_confirmation) %>
  </div>

  <div class="actions">
    <%= f.submit t 'app.submit' %>
  </div>
<% end %>

app/views/users/account_edit_new.html.erb
<section class="c-account-edit-card u-margin-bottom-large">
  <aside class="c-account-edit__tabs o-list-bare">
    <div clas="o-list-bare__item">
      <%= link_to t('app.user_profile.edit_profile'), account_edit_new_path, class: "c-link--silence c-account-edit_tab-item c-account-edit_tab-item--actived" %>
    </div>
    <div class="o-list-bare__item">
      <%= link_to t('app.user_profile.change_password'), new_account_password_change_path, class: "c-link--silence c-account-edit_tab-item" %>
    </div>
  </aside>

  <article class="c-account-edit">

  <div class="c-account-edit__avatar-edit">
    <%= gravatar_for(current_user, size: 38) %>
    <span class="u-h4"><%= current_user.name %></span>
  </div>

  <%= form_for(@user, url: account_edit_path, method: :patch, html: { class: 'c-form c-form--primary c-form--block o-wrapper c-account-edit-form' }) do |f| %>

    <div class="c-account-edit-form__field">
      <div class="c-account-edit-form__aside"><%= f.label User.human_attribute_name(:name) %></div>
      <div class="c-account-edit-form__input"><%= f.text_field :name, class: 'c-form__control', placeholder: User.human_attribute_name(:name)%></div>
    </div>

    <div class="c-account-edit-form__field">
      <div class="c-account-edit-form__aside"><%= f.label User.human_attribute_name(:email) %></div>
      <div class="c-account-edit-form__input"><%= f.text_field :email, class: 'c-form__control', placeholder: User.human_attribute_name(:email) %></div>
    </div>

    <div class="c-account-edit-form__field">
      <div class="c-account-edit-form__aside"></div>
      <div><%= f.submit t('app.submit'), class: 'c-btn c-btn--small c-btn--primary' %></div>
    </div>

    <div class="c-account-edit-form__field">
      <div class="c-account-edit-form__aside"></div>
      <%= render 'shared/error_messages', object: @user %>
    </div>

  <% end %>

  </article>
</section>

app/views/users/followers.html.erb
<section class="o-wrapper">

  <section class="o-wrapper c-card c-card--primary u-margin-bottom-large">
    <h2 class="u-margin-small u-h6"><%= t('app.followers') %></h2>
    <% @user.followers.each do |user| %>

      <article class="o-media o-media-small u-padding-small">
        <header class="c-post__header">

          <a class="c-post__avatar c-link--silence u-margin-right-small" href=<%="/#{user.name}"%> >
            <%= gravatar_for(user, size: 30) %>
          </a>
          <a class="c-post__owner c-link--silence" href=<%="/#{user.name}" %> >
            <strong ><%= user.name %></strong>
          </a>

          <% if user_signed_in? && current_user.id != user.id %>
            <% if current_user.following?(user) %>
              <%= button_to  t('app.unfollow'), follow_users_path(followed_id: user), method: :delete, class: 'c-btn c-btn--small c-btn--secondary' %>
            <% else %>
              <%= button_to  t('app.follow'), follow_users_path(followed_id: user), method: :post, class: 'c-btn c-btn--small c-btn--primary' %>
            <% end %>
          <% end %>

        </header>

      </article>

    <% end %>
  </section>
</section>

app/views/users/following.html.erb
<section class="o-wrapper">

  <section class="o-wrapper c-card c-card--primary u-margin-bottom-large">
    <h2 class="u-margin-small u-h6"><%= t('app.following') %></h2>
    <% @user.following.each do |user| %>

      <article class="o-media o-media-small u-padding-small">
        <header class="c-post__header">

          <a class="c-post__avatar c-link--silence u-margin-right-small" href=<%="/#{user.name}"%> >
            <%= gravatar_for(user, size: 30) %>
          </a>
          <a class="c-post__owner c-link--silence" href=<%="/#{user.name}" %> >
            <strong ><%= user.name %></strong>
          </a>

          <% if user_signed_in? && current_user.id != user.id %>
            <% if current_user.following?(user) %>
              <%= button_to  t('app.unfollow'), follow_users_path(followed_id: user), method: :delete, class: 'c-btn c-btn--small c-btn--secondary' %>
            <% else %>
              <%= button_to  t('app.follow'), follow_users_path(followed_id: user), method: :post, class: 'c-btn c-btn--small c-btn--primary' %>
            <% end %>
          <% end %>

        </header>

      </article>

    <% end %>
  </section>
</section>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<div class="o-wrapper">
  <h2>Instagram</h2>
  <p>注册 Instagram, 分享精彩视界</p>
  <%= render 'signup_form', user: @user %>
  <p><small>注册即表示你同意我们 条款 和隐私权政策</small></p>
</div>
<div class="o-wrapper">
  <p>
    有账户了？
    <%= link_to  "请登录", login_url %>
  </p>
</div>

app/views/users/password_change_new.html.erb
<section class="c-account-edit-card u-margin-bottom-large">
  <aside class="c-account-edit__tabs o-list-bare">
    <div clas="o-list-bare__item">
      <%= link_to t('app.user_profile.edit_profile'), new_account_edit_path, class: "c-link--silence c-account-edit_tab-item" %>
    </div>
    <div class="o-list-bare__item">
      <%= link_to t('app.user_profile.change_password'), new_account_password_change_path, class: "c-link--silence c-account-edit_tab-item c-account-edit_tab-item--actived" %>
    </div>
  </aside>

  <article class="c-account-edit">

  <div class="c-account-edit__avatar-edit">
    <%= gravatar_for(current_user, size: 38) %>
    <span class="u-h4"><%= current_user.name %></span>
  </div>

  <%= form_for(@user, url: account_password_change_path, method: :post, html: { class: 'c-form c-form--primary c-form--block o-wrapper c-account-edit-form' }) do |f| %>

    <div class="c-account-edit-form__field">
      <div class="c-account-edit-form__aside">
        <%= f.label t('app.user_profile.old_password') %>
      </div>
      <div class="c-account-edit-form__input">
        <%= f.password_field :current_password, class: 'c-form__control', placeholder: User.human_attribute_name(:current_password) %>
      </div>
    </div>

    <div class="c-account-edit-form__field">
      <div class="c-account-edit-form__aside">
        <%= f.label t('app.user_profile.new_password') %>
      </div>
      <div class="c-account-edit-form__input">
        <%= f.password_field :password, class: 'c-form__control', placeholder: User.human_attribute_name(:password) %>
      </div>
    </div>

    <div class="c-account-edit-form__field">
      <div class="c-account-edit-form__aside">
        <%= f.label t('app.user_profile.new_password_again') %>
      </div>
      <div class="c-account-edit-form__input">
        <%= f.password_field :password_confirmation, class: 'c-form__control', placeholder: User.human_attribute_name(:password_confirmation) %>
      </div>
    </div>

    <div class="c-account-edit-form__field">
      <div class="c-account-edit-form__aside"></div>
      <div><%= f.submit t('app.user_profile.change_password'), class: 'c-btn c-btn--small c-btn--primary' %></div>
    </div>

    <div class="c-account-edit-form__field">
      <div class="c-account-edit-form__aside"></div>
      <%= render 'shared/error_messages', object: @user %>
    </div>

  <% end %>

  </article>
</section>

app/views/users/show.html.erb
<article class='c-user-page u-padding-vertical-large u-padding-horizontal' data-ui-component="user-page">

  <header class='c-user-profile u-margin-right' data-ui-component="user-profile">

    <div class='c-user-profile__change-avatar u-margin-right'>
      <%= gravatar_for @user, size: 150, class_name: 'c-user-profile__avatar u-margin-horizontal-large' %>
    </div>

    <div class='c-user-profile__info'>

      <div class='c-user-profile__row'>
        <h1 class='c-user-profile__unit c-user-profile__username u-margin-right u-h2'><%= @user.name %></h1>
        <% if user_signed_in? && current_user.id != @user.id %>
          <% if current_user.following?(@user) %>
            <%= button_to t('app.unfollow'), follow_users_path(followed_id: @user), method: :delete, class: 'c-btn c-btn--small c-btn--secondary c-user-profile__unit', form_class: 'c-user-profile__unit'%>
          <% else %>
            <%= button_to  t('app.follow'), follow_users_path(followed_id: @user), class: 'c-btn c-btn--small c-btn--secondary c-user-profile__unit', form_class: 'c-user-profile__unit'%>
          <% end %>
        <% end %>
        <% if user_signed_in? && current_user.id == @user.id %>
          <%= link_to  t('app.sign_out'), sign_out_path, method: :delete,  class: 'c-btn c-btn--small c-btn--secondary c-user-profile__unit u-margin-right-small' %>
          <%= link_to  t('app.user_profile.edit_profile'), new_account_edit_path, class: 'c-btn c-btn--small c-btn--secondary c-user-profile__unit' %>
        <% end %>
      </div>

      <ul class='c-user-profile__row'>

        <li class='o-list-inline__item c-user-profile__unit u-h6 u-margin-right-large'><%= t('app.user_profile.posts_desc', count: @user.posts.count) %></li>
        <a class="c-link c-link--silence" href=<%= user_followers_path(name: @user.name) %> >
          <li class='o-list-inline__item c-user-profile__unit u-h6 u-margin-right-large'><%= t('app.user_profile.followers_desc', count: @user.followers.count) %></li>
        </a>
        <a class="c-link c-link--silence" href=<%= user_following_path(name: @user.name) %> >
          <li class='o-list-inline__item c-user-profile__unit u-h6 u-margin-right-large'><%= t('app.user_profile.following_desc', count: @user.following.count) %></li>
        </a>

      </ul>

    </div>

  </header>

  <section>

    <main class="c-user-posts u-margin-vertical-large" id="posts-user">

      <%= render 'posts/grid_posts', posts: @posts %>

    </main>

    <% unless @posts.last_page? %>
      <div class="pagination u-align-center u-margin-bottom">
        <%= link_to_next_page(@posts, t('app.loadmore'), remote: true, class: 'c-btn c-btn--primary c-btn--small o-wrapper') %>
      </div>
    <% end %>

  </section>

</article>

app/views/users/show.js.erb
$("#posts-user").append("<%= j render('posts/grid_posts', posts: @posts) %>");

// Update pagination link
<% if @posts.last_page? %>
  $('.pagination').html("");
<% else %>
  $('.pagination').html("<%=j(link_to_next_page(@posts, t('app.loadmore'), remote: true, class: 'c-btn c-btn--primary c-btn--small o-wrapper')) %>");
<% end %>