config/routes.rb
Rails.application.routes.draw do
  # DEVISE
  devise_for :users,
             controllers: {
               passwords: 'users/passwords',
               confirmations: 'users/confirmations'
             },
             only: [:passwords, :confirmations]

  devise_scope :user do
    get    'sign_up',  to: 'users/registrations#new'
    post   'sign_up',  to: 'users/registrations#create'
    get    'sign_in',  to: 'users/sessions#new'
    post   'sign_in',  to: 'users/sessions#create'
    delete 'sign_out', to: 'users/sessions#destroy'
  end

  get   '/:name',                  to: 'users#show'

  get   '/:name/followers',        to: 'users#followers',           as: 'user_followers'
  get   '/:name/following',        to: 'users#following',           as: 'user_following'
  get   'account/password/change', to: 'users#password_change_new', as: 'new_account_password_change'
  post  'account/password/change', to: 'users#password_change',     as: 'account_password_change'
  post  'set_locale', to: 'home#set_locale', as: 'set_locale'


  resources :users, only: [:edit, :update] do
    collection do
      post   :follow, to: 'users#follow'
      delete :follow, to: 'users#unfollow'
    end

    member do
      post   :like, to: 'users#like'
      delete :like, to: 'users#unlike'
    end

    resources :posts, only: [:new, :create]
  end

  resources :account_edits, only: [:new, :create]

  resources :posts, only: [:update, :destroy] do
    resources :comments, only: [:new, :create]
  end

  resources :comments, only: [:update, :destroy]

  # post   :like_action, to: 'users#like', as: 'user_like'
  # delete :like_action, to: 'users#unlike', as: 'user_unlike'

  root to: 'home#index'
  # Advanced
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="u-text-color-red">
    <ul class="o-list-bare">
      <% object.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
        <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<section class="footer c-navbar c-navbar--glost o-wrapper u-margin-bottom-large" data-ui-component="site-footer">

  <div class="o-wrapper c-navbar__item u-padding-horizontal-large">
    <div class="o-list-inline c-navbar__item c-navbar__item--align-left">
      <a class="o-list-inline__item u-padding-right-tiny"><small><%= t('app.about_us').upcase %></small></a>
      <a class="o-list-inline__item u-padding-right-tiny"><small><%= t('app.support').upcase %></small></a>
      <a class="o-list-inline__item u-padding-right-tiny"><small><%= t('app.blog').upcase %></small></a>
      <a class="o-list-inline__item u-padding-right-tiny"><small><%= t('app.press').upcase %></small></a>
      <a class="o-list-inline__item u-padding-right-tiny"><small><%= t('app.api').upcase %></small></a>
      <a class="o-list-inline__item u-padding-right-tiny"><small><%= t('app.jobs').upcase %></small></a>
      <a class="o-list-inline__item u-padding-right-tiny"><small><%= t('app.privacy').upcase %></small></a>
      <a class="o-list-inline__item u-padding-right-tiny"><small><%= t('app.terms').upcase %></small></a>
      <a class="o-list-inline__item u-padding-right-tiny"><small><%= t('app.directory').upcase %></small></a>
      <a class="o-list-inline__item c-language">
        <small><%= t('app.language').upcase %></small>
        <%= form_tag(set_locale_path, method: :post, class: 'c-form c-language-select') do %>
          <select name='locale' id="locale" class="c-form__control" onChange="this.form.submit()">
            <option value="" disabled selected>Select language</option>
            <% I18n.available_locales.each do |locale| %>
              <option value=<%= locale %> > <%= t locale %> </<option>
            <% end %>
          </select>
        <% end %>
      </a>
    </div>
    <div class="u-text-color-notice c-navbar__item--align-right">
      <strong>© 2017 INSTAGRAM</strong>
    </div>
  </div>

</section>

app/views/shared/_header.html.erb
<section class="u-margin-bottom-large c-navbar c-header">

  <div class="c-navbar__item c-header__inner u-padding-vertical u-padding-horizontal-large">

    <div class="c-navbar__item c-navbar__item--align-left c-navbar__item--important">
      <%= link_to '', root_path, class: 'c-icon-main c-icon-main__secondary' %>
    </div>

    <div class="c-navbar__item c-navbar__item--not-so-important">
      <form class="c-navbar__item c-form c-form--primary">
        <input class="c-form__control" type="search" placeholder=<%= t('app.search') + " ..." %> />
      </form>
    </div>

    <div class="c-navbar__item c-navbar__item--align-right">
      <div class="c-navbar__item c-navbar__item--align-right o-list-inline">
        <% if user_signed_in? %>
          <%= link_to '', root_path, class: 'u-margin-right o-list-inline__item c-icon-main c-icon-main__compass' %>
          <%= link_to '', root_path, class: 'u-margin-right o-list-inline__item c-icon-main c-icon-main__activity' %>
          <%= link_to '', "/#{current_user.name}", class: 'o-list-inline__item c-icon-main c-icon-main__profile' %>
        <% else %>
          <%= link_to t('app.sign_in'), sign_in_path, class: 'o-list-inline__item c-link c-link--primary' %>
        <% end %>

      </div>
    </div>

  </div>

</section>