config/routes.rb
Rails.application.routes.draw do
  # DEVISE
  devise_for :users,
             controllers: {
               passwords: 'users/passwords',
               confirmations: 'users/confirmations'
             },
             only: [:passwords, :confirmations]

  devise_scope :user do
    get    'sign_up',  to: 'users/registrations#new'
    post   'sign_up',  to: 'users/registrations#create'
    get    'sign_in',  to: 'users/sessions#new'
    post   'sign_in',  to: 'users/sessions#create'
    delete 'sign_out', to: 'users/sessions#destroy'
  end

  get   '/:name',                  to: 'users#show'

  get   '/:name/followers',        to: 'users#followers',           as: 'user_followers'
  get   '/:name/following',        to: 'users#following',           as: 'user_following'
  get   'account/password/change', to: 'users#password_change_new', as: 'new_account_password_change'
  post  'account/password/change', to: 'users#password_change',     as: 'account_password_change'
  post  'set_locale', to: 'home#set_locale', as: 'set_locale'


  resources :users, only: [:edit, :update] do
    collection do
      post   :follow, to: 'users#follow'
      delete :follow, to: 'users#unfollow'
    end

    member do
      post   :like, to: 'users#like'
      delete :like, to: 'users#unlike'
    end

    resources :posts, only: [:new, :create]
  end

  resources :account_edits, only: [:new, :create]

  resources :posts, only: [:update, :destroy] do
    resources :comments, only: [:new, :create]
  end

  resources :comments, only: [:update, :destroy]

  # post   :like_action, to: 'users#like', as: 'user_like'
  # delete :like_action, to: 'users#unlike', as: 'user_unlike'

  root to: 'home#index'
  # Advanced
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  # RELATIONS
  belongs_to :owner, class_name: 'User', foreign_key: 'user_id'
  has_many :comments
  has_many :likes, class_name: 'LikeAction', foreign_key: 'post_id'


  # QUERYs
  default_scope -> { order(created_at: :desc) }

  # VALIDATIONS
  validates :user_id, presence: true
  validates :picture, presence: true
  validate  :picture_size

  mount_uploader :picture, PostPictureUploader

  private

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, 'should be less than 5MB')
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.build(post_params)
    @post.save
    redirect_to request.referer || root_url
  end

  def destory
  end

  private

  def post_params
    params.require(:post).permit(:content, :user_id, :picture)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_empty_post_users.html.erb
<a href="" class="c-post-click c-post--users u-margin-right">

  <div class="c-post__body">

  </div>

  <div class="c-post__base">

  </div>
</a>

app/views/posts/_grid_posts.html.erb
<% posts.each.with_index do |post, index| %>

  <% if index % 3 == 0 %>
    <div class="c-users-posts__row u-margin-bottom">
  <% end %>

  <%= render 'posts/post_users', post: post %>

  <% if index == posts.count - 1 && posts.count % 3 != 0 %>

    <% (3 - posts.count % 3).times do %>
      <%= render 'posts/empty_post_users' %>
    <% end %>

  <% end %>

  <% if index % 3 == 2 %>
    </div>
  <% end %>

<% end %>

app/views/posts/_new_post.html.erb
<%= form_for( current_user.posts.build, url: user_posts_path(current_user), html: {class: "o-wrapper c-form c-form--primary c-form--block c-card c-card--primary u-padding u-margin-bottom-large"}) do |f| %>

  <%= render 'shared/error_messages', object: post %>

  <div class="c-form__field">
    <%= f.file_field :picture, class: 'c-form__control' %>
  </div>

  <div class="c-form__field">
    <%= f.text_field :content, class: 'c-form__control', placeholder: "输入..." %>
  </div>
  
  <div class="c-form__field">
    <%= f.submit 'Create post', class: 'c-form__control c-btn c-btn--primary c-btn--tiny' %>
  </div>

<% end %>

app/views/posts/_post.html.erb
<article class="u-margin-bottom-large c-post c-post--main" data-ui-component="post">

  <header class="c-post__header u-padding-horizontal u-padding-vertical-small">

    <a class="c-post__avatar c-link--silence u-margin-right-small" href=<%="/#{post.owner.name}"%> >
      <%= gravatar_for(post.owner, size: 30) %>
    </a>
    <a class="c-post__owner c-link--silence" href=<%="/#{post.owner.name}" %> >
      <strong ><%= post.owner.name %></strong>
    </a>

    <small class="c-post__posted-at"><%= time_ago_in_words(post.created_at) %></small>

  </header>

  <div class="c-post__body">
    <%= image_tag  post.picture.url, class_name: 'c-post__picture' %>
  </div>

  <div class="c-post__attr u-padding">
    <% if post.likes.any? %>
      <div class="o-media o-media--small">
        <div class="o-media__body">
          <strong><%= t 'app.like_desc', count: post.likes.count %></strong>
        </div>
      </div>
    <% end %>
    <div class="o-media o-media--small">
      <div class="o-media__body">

        <a class="c-link--silence" href=<%= "/#{post.owner.name}" %> >
          <strong><%= post.owner.name %></strong>
        </a>
        <span><%= post.content %></span>

      </div>
    </div>
  </div>

  <footer class="u-padding-horizontal">

    <% if post.reload.comments.any? %>
    <ul class="a-comment-list u-margin-top" data-ui-component="comments-list">

      <%= render post.reload.comments, post: post %>

    </ul>
    <% end %>

    <%= render 'comments/new_comment', post: post %>

  </footer>

</article>

app/views/posts/_post_users.html.erb
<a href="" class="c-post-click c-post--users u-margin-right">

  <div class="c-post__body">

    <%= image_tag  post.picture.middle.url, class: 'c-post__picture', alt: post.content %>

  </div>

  <div class="c-post__base">

  </div>
</a>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destory.html.erb
<h1>Posts#destory</h1>
<p>Find me in app/views/posts/destory.html.erb</p>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>